//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport.ObtenerTicket {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ObtenerTicket.ObtenerTicketSoap")]
    public interface ObtenerTicketSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tk del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTokenPersonaBest", ReplyAction="*")]
        Sport.ObtenerTicket.ObtenerTokenPersonaBestResponse ObtenerTokenPersonaBest(Sport.ObtenerTicket.ObtenerTokenPersonaBestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTokenPersonaBest", ReplyAction="*")]
        System.Threading.Tasks.Task<Sport.ObtenerTicket.ObtenerTokenPersonaBestResponse> ObtenerTokenPersonaBestAsync(Sport.ObtenerTicket.ObtenerTokenPersonaBestRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tk del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTokenFacturaBest", ReplyAction="*")]
        Sport.ObtenerTicket.ObtenerTokenFacturaBestResponse ObtenerTokenFacturaBest(Sport.ObtenerTicket.ObtenerTokenFacturaBestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTokenFacturaBest", ReplyAction="*")]
        System.Threading.Tasks.Task<Sport.ObtenerTicket.ObtenerTokenFacturaBestResponse> ObtenerTokenFacturaBestAsync(Sport.ObtenerTicket.ObtenerTokenFacturaBestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTokenPersonaBestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTokenPersonaBest", Namespace="http://tempuri.org/", Order=0)]
        public Sport.ObtenerTicket.ObtenerTokenPersonaBestRequestBody Body;
        
        public ObtenerTokenPersonaBestRequest() {
        }
        
        public ObtenerTokenPersonaBestRequest(Sport.ObtenerTicket.ObtenerTokenPersonaBestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerTokenPersonaBestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tk;
        
        public ObtenerTokenPersonaBestRequestBody() {
        }
        
        public ObtenerTokenPersonaBestRequestBody(string tk) {
            this.tk = tk;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTokenPersonaBestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTokenPersonaBestResponse", Namespace="http://tempuri.org/", Order=0)]
        public Sport.ObtenerTicket.ObtenerTokenPersonaBestResponseBody Body;
        
        public ObtenerTokenPersonaBestResponse() {
        }
        
        public ObtenerTokenPersonaBestResponse(Sport.ObtenerTicket.ObtenerTokenPersonaBestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerTokenPersonaBestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerTokenPersonaBestResult;
        
        public ObtenerTokenPersonaBestResponseBody() {
        }
        
        public ObtenerTokenPersonaBestResponseBody(string ObtenerTokenPersonaBestResult) {
            this.ObtenerTokenPersonaBestResult = ObtenerTokenPersonaBestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTokenFacturaBestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTokenFacturaBest", Namespace="http://tempuri.org/", Order=0)]
        public Sport.ObtenerTicket.ObtenerTokenFacturaBestRequestBody Body;
        
        public ObtenerTokenFacturaBestRequest() {
        }
        
        public ObtenerTokenFacturaBestRequest(Sport.ObtenerTicket.ObtenerTokenFacturaBestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerTokenFacturaBestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tk;
        
        public ObtenerTokenFacturaBestRequestBody() {
        }
        
        public ObtenerTokenFacturaBestRequestBody(string tk) {
            this.tk = tk;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTokenFacturaBestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTokenFacturaBestResponse", Namespace="http://tempuri.org/", Order=0)]
        public Sport.ObtenerTicket.ObtenerTokenFacturaBestResponseBody Body;
        
        public ObtenerTokenFacturaBestResponse() {
        }
        
        public ObtenerTokenFacturaBestResponse(Sport.ObtenerTicket.ObtenerTokenFacturaBestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerTokenFacturaBestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerTokenFacturaBestResult;
        
        public ObtenerTokenFacturaBestResponseBody() {
        }
        
        public ObtenerTokenFacturaBestResponseBody(string ObtenerTokenFacturaBestResult) {
            this.ObtenerTokenFacturaBestResult = ObtenerTokenFacturaBestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ObtenerTicketSoapChannel : Sport.ObtenerTicket.ObtenerTicketSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObtenerTicketSoapClient : System.ServiceModel.ClientBase<Sport.ObtenerTicket.ObtenerTicketSoap>, Sport.ObtenerTicket.ObtenerTicketSoap {
        
        public ObtenerTicketSoapClient() {
        }
        
        public ObtenerTicketSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ObtenerTicketSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObtenerTicketSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObtenerTicketSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sport.ObtenerTicket.ObtenerTokenPersonaBestResponse Sport.ObtenerTicket.ObtenerTicketSoap.ObtenerTokenPersonaBest(Sport.ObtenerTicket.ObtenerTokenPersonaBestRequest request) {
            return base.Channel.ObtenerTokenPersonaBest(request);
        }
        
        public string ObtenerTokenPersonaBest(string tk) {
            Sport.ObtenerTicket.ObtenerTokenPersonaBestRequest inValue = new Sport.ObtenerTicket.ObtenerTokenPersonaBestRequest();
            inValue.Body = new Sport.ObtenerTicket.ObtenerTokenPersonaBestRequestBody();
            inValue.Body.tk = tk;
            Sport.ObtenerTicket.ObtenerTokenPersonaBestResponse retVal = ((Sport.ObtenerTicket.ObtenerTicketSoap)(this)).ObtenerTokenPersonaBest(inValue);
            return retVal.Body.ObtenerTokenPersonaBestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sport.ObtenerTicket.ObtenerTokenPersonaBestResponse> Sport.ObtenerTicket.ObtenerTicketSoap.ObtenerTokenPersonaBestAsync(Sport.ObtenerTicket.ObtenerTokenPersonaBestRequest request) {
            return base.Channel.ObtenerTokenPersonaBestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sport.ObtenerTicket.ObtenerTokenPersonaBestResponse> ObtenerTokenPersonaBestAsync(string tk) {
            Sport.ObtenerTicket.ObtenerTokenPersonaBestRequest inValue = new Sport.ObtenerTicket.ObtenerTokenPersonaBestRequest();
            inValue.Body = new Sport.ObtenerTicket.ObtenerTokenPersonaBestRequestBody();
            inValue.Body.tk = tk;
            return ((Sport.ObtenerTicket.ObtenerTicketSoap)(this)).ObtenerTokenPersonaBestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sport.ObtenerTicket.ObtenerTokenFacturaBestResponse Sport.ObtenerTicket.ObtenerTicketSoap.ObtenerTokenFacturaBest(Sport.ObtenerTicket.ObtenerTokenFacturaBestRequest request) {
            return base.Channel.ObtenerTokenFacturaBest(request);
        }
        
        public string ObtenerTokenFacturaBest(string tk) {
            Sport.ObtenerTicket.ObtenerTokenFacturaBestRequest inValue = new Sport.ObtenerTicket.ObtenerTokenFacturaBestRequest();
            inValue.Body = new Sport.ObtenerTicket.ObtenerTokenFacturaBestRequestBody();
            inValue.Body.tk = tk;
            Sport.ObtenerTicket.ObtenerTokenFacturaBestResponse retVal = ((Sport.ObtenerTicket.ObtenerTicketSoap)(this)).ObtenerTokenFacturaBest(inValue);
            return retVal.Body.ObtenerTokenFacturaBestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sport.ObtenerTicket.ObtenerTokenFacturaBestResponse> Sport.ObtenerTicket.ObtenerTicketSoap.ObtenerTokenFacturaBestAsync(Sport.ObtenerTicket.ObtenerTokenFacturaBestRequest request) {
            return base.Channel.ObtenerTokenFacturaBestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sport.ObtenerTicket.ObtenerTokenFacturaBestResponse> ObtenerTokenFacturaBestAsync(string tk) {
            Sport.ObtenerTicket.ObtenerTokenFacturaBestRequest inValue = new Sport.ObtenerTicket.ObtenerTokenFacturaBestRequest();
            inValue.Body = new Sport.ObtenerTicket.ObtenerTokenFacturaBestRequestBody();
            inValue.Body.tk = tk;
            return ((Sport.ObtenerTicket.ObtenerTicketSoap)(this)).ObtenerTokenFacturaBestAsync(inValue);
        }
    }
}
